// public/components/Sidebar/Sidebar.tsx
import * as React from 'react';
import {Linked} from '../Linked/Linked';

import './Sidebar.scss';

export class Sidebar extends React.Component<any, any> {
  render() {
    return (
      <div className="w3-sidebar w3-light-grey w3-bar-block left__navbar">
        <Linked pathTo="/projects">
          <p className="w3-bar-item w3-button">Projects</p>
        </Linked>
        <Linked pathTo="/tasks">
          <p className="w3-bar-item w3-button">Tasks</p>
        </Linked>
      </div>
    );
  }
}

// src/components/sidebar/sidebar.component.ts
import * as Vue from 'vue';
import Component from 'vue-class-component';

import './sidebar.component.scss';

@Component({
  template: `
       <div class="w3-sidebar w3-light-grey w3-bar-block left__navbar">
          <router-link to="/main">
            <a class="w3-bar-item w3-button">Главная</a>
          </router-link>
          <router-link to="/tasks">
            <a class="w3-bar-item w3-button">Задачи</a>
          </router-link>
          <router-link to="/calendar">
            <a class="w3-bar-item w3-button">Календарь</a>
          </router-link>
          <router-view></router-view>
       </div>
  `
})
export class SidebarComponent extends Vue {
}
